version: '3.9'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: warvox
      POSTGRES_DB: warvox
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 30
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  warvox:
    image: sans1241/warvox
    environment:
      DB_PORT_5432_TCP_ADDR: db
      VOXUSER: warvox
      VOXPASS: changeme
      ADMINUSER: admin
      ADMINPASS: changeme
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "7777:7777"
    volumes:
      - ./setup.sh:/setup.sh
